== Mentoring Projekt
Wir werden an einer App arbeiten, um die unterschiedlichen Aspekten des Programmieren zu berücksichtigen: Backend, Frontend, DB, Infrastruktur, usw.

=== Erstes Projekt
Bestimmte Punkte sind noch zu definieren: 
* Wofür soll die App dienen? Wie wird die App heißen?
* Als Beispiel: https://realworld-docs.netlify.app/docs/intro/
* Welche Technologien wollen wir verwenden?

=== Erledigt
* Erstes Repo mit einer Readme in GitHub
* Erstes Gespräch und Gedanken über die App
* GraalVM gelernt
* GraalVM (Video schauen)
* 2 Repos und intelliJ Community (readme und spielwiese)
* Java LTS Version: 8 vs. 11 -> Unterschied zwischen Versionen, was hat sich geändert?
  https://www.digitalocean.com/community/tutorials/java-11-features
* lambda-Beispiele mit Consumer, Predicate und Suplier provieren (+Optional)
  https://medium.com/swlh/understanding-java-8s-consumer-supplier-predicate-and-function-c1889b9423d
* Tabelle für die Lambdas in spielwiese erzeugen: Was machen sie? Was komm rein und raus? usw.
* Beispiele mit Functional, Bifunction und Operator

=== To Dos

* entwickler.de anschauen
* Optionals:

  ** 3 Dtos für die Tests vorbereiten

  ** Use Cases in einer Tabelle schreiben

  ** Beispiel mit folgenden Methoden: ifPresent(); ifPresentOrElse(); map(); orElseGet(); orElseThrow(); or();

  
=== Themen für nächste Woche
* Stream API

=== Pläne für Januar 2023
* evtl. Stream API weiter
* Exceptions (Trickkiste)
* Date & Time: was sich in Java 8 geändert hat und warum
* Schulungen
